export * from './BodyChart';
export * from './BodyChartWithBtn';
export * from "./HeaderMenu"
export * from "./InputMenu"
export * from "./MyExercise"
export * from './RecordMenu';
export * from './RecordPhoto';
export * from './SpanBtns';
export * from './TopPhoto';